name: Github actions demo
on: push
jobs:
  action-demo:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout the code
        uses: actions/checkout@v4
      - name: Print index.html file
        run: cat index.html
        
      
