name: context variables demo
on: push
jobs:
  context-demo:
    runs-on: ubuntu-latest
    steps:
      - name: use the context variable
        run: 
          echo " This workflow is triggered by ${{github.actor}}
          echo " The repository name is ${{github.repository}}
          ehco " The brach name is ${{ github.ref_name }} 
          
      - name: Print all variables of github
        run: echo "${{ toJson(github) }}"
