name: Inputs demo

on:
  workflow_dispatch:
    inputs:
      environment:
        description: choose the env to deploy
        required: true
        default: dev
        type: choice
        options:
          - dev
          - test
          - prod

      tag:
        description: choose the git tag to deploy
        required: true
        type: string

jobs:
  inputs-demo:
    runs-on: ubuntu-latest
    steps:
      - name: deploy the app
        run: echo "Deploying ${{ inputs.tag }} to ${{ inputs.environment }}"
