name: Or condition demo
on: push
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Run for natesan or gowcy
        if: ${{ (github.actor == 'Natesh'|| github.actor == 'Gowcy') }} 
        run: echo "It is triggered by either Natesh or Gowcy"
  
